<?php declare(strict_types=1);

/**
 * @package Simple Mod Maker
 * @link https://github.com/dragomano/Simple-Mod-Maker
 * @author Bugo <bugo@dragomano.ru>
 * @copyright 2022-2026 Bugo
 * @license https://opensource.org/licenses/BSD-3-Clause BSD
 *
 * @version 1.0
 */

namespace Bugo\SimpleModMaker;

if (! defined('SMF'))
	die('No direct access...');

namespace Bugo\SimpleModMaker;

use Bugo\SimpleModMaker\Hooks\HookFactory;
use Nette\PhpGenerator\ClassType;
use Nette\PhpGenerator\Method;
use Nette\PhpGenerator\PhpFile;
use Nette\PhpGenerator\PhpNamespace;

class Generator
{
	public function generate(array &$skeleton, string $classname, string $snakeName): array
	{
		[$namespace, $class] = $this->createClassStructure($skeleton, $classname);

		$this->generateHooksMethods($class, $skeleton, $classname, $snakeName);
		$this->generateLegacyTaskMethods($class, $skeleton);
		$this->generateSettingsMethods($class, $skeleton, $classname, $snakeName);

		$tasks = [];

		$this->generateScheduledTasks($tasks, $skeleton, $classname);
		$this->generateBackgroundTasks($tasks, $skeleton, $classname);
		$this->generateTaskExamples($class, $skeleton, $classname, $tasks);

		$filename = (empty($skeleton['make_dir']) ? $skeleton['filename'] : 'Integration') . '.php';
		$content  = $this->getGeneratedContent($namespace, $filename, $skeleton);

		return [
			'content' => $content,
			'tasks'   => $tasks,
		];
	}

	private function createClassStructure(array $skeleton, string $classname): array
	{
		if (empty($skeleton['make_dir'])) {
			$namespace = new PhpNamespace($skeleton['author']);
			$class = $namespace->addClass($classname);
		} else {
			$namespace = new PhpNamespace($skeleton['author'] . '\\' . $classname);
			$class = $namespace->addClass('Integration');
		}

		if ($skeleton['smf_target_version'] === '3.0') {
			$this->addSMF3Imports($namespace);
		}

		$class->addComment('Generated by ' . SMM_NAME);

		if ($skeleton['smf_target_version'] === '2.1/3.0') {
			$class->addComment(PHP_EOL . 'Try to use https://github.com/dragomano/smf-compat package to make your mod compatible with both SMF versions');
		}

		return [$namespace, $class];
	}

	private function addSMF3Imports(PhpNamespace $namespace): void
	{
		$namespace->addUse('SMF\Actions\Admin\ACP');
		$namespace->addUse('SMF\Config');
		$namespace->addUse('SMF\Db\DatabaseApi', 'Db');
		$namespace->addUse('SMF\Lang');
		$namespace->addUse('SMF\Menu');
		$namespace->addUse('SMF\Theme');
		$namespace->addUse('SMF\User');
		$namespace->addUse('SMF\Utils');
	}

	private function generateHooksMethods(ClassType $class, array $skeleton, string $classname, string $snakeName): void
	{
		global $context;

		$hooks = $class->addMethod('hooks')->setReturnType('void');

		if (empty($skeleton['hooks'])) {
			$hooks->addBody("// add_integration_function('integrate_hook_name', self::class . '::methodName#', false, __FILE__);");
		}

		foreach ($skeleton['hooks'] as $hook) {
			$methodName = $this->getMethodName($hook);
			$hooks->addBody("add_integration_function(?, self::class . '::?#', false, __FILE__);", [$hook, $methodName])
				->addComment("@uses $methodName");

			$method = $class->addMethod($methodName);

			$hookInstance = HookFactory::create($hook, $context, $classname, $snakeName);

			if ($hookInstance !== null) {
				$parameters = $hookInstance->getParameters();
				foreach ($parameters as $param => $data) {
					$parameter = isset($data[2]) ? $method->addParameter($param, $data[2]) : $method->addParameter($param);
					$parameter->setType($data[0]);

					if (! empty($data[1])) {
						$parameter->setReference();
					}
				}

				$method->setReturnType($hookInstance->getReturnType());

				$bodyLines = $hookInstance->getBody();
				foreach ($bodyLines as $body) {
					$method->addBody($body);
				}
			}

			if ($hook === Hook::GENERAL_MOD_SETTINGS && $skeleton['settings_area'] === 1) {
				$this->fillConfigVars($method, $skeleton, $snakeName);
			}
		}
	}

	private function generateLegacyTaskMethods(ClassType $class, array $skeleton): void
	{
		foreach ($skeleton['legacy_tasks'] as $task) {
			$taskMethod = $class->addMethod($task['method']);
			$hookName = empty($task['regularity']) ? Hook::DAILY_MAINTENANCE : Hook::WEEKLY_MAINTENANCE;
			$taskMethod->addComment("Simple task via $hookName hook");
			$taskMethod->setReturnType('void');

			if ($skeleton['smf_target_version'] !== '3.0') {
				$taskMethod->addBody("global \$smcFunc;" . PHP_EOL);
			}

			$taskMethod->addBody("// Add your code here");
		}
	}

	private function generateSettingsMethods(ClassType $class, array &$skeleton, string $classname, string $snakeName): void
	{
		$hookKeys = array_flip($skeleton['hooks']);

		if ($skeleton['settings_area'] === 2) {
			$this->generateSettingsArea2($class, $skeleton, $classname, $snakeName, $hookKeys);
		}

		if ($skeleton['settings_area'] === 3) {
			$this->generateSettingsArea3($class, $skeleton, $classname, $snakeName);
		}
	}

	private function generateSettingsArea2(ClassType $class, array &$skeleton, string $classname, string $snakeName, array $hookKeys): void
	{
		$settings = $class->addMethod('settings');

		if (isset($hookKeys[Hook::ADMIN_SEARCH])) {
			$settings->addComment('@return array|void');
			$parameter = $settings->addParameter('return_config', false);
			$parameter->setType('bool');
		}

		if ($skeleton['smf_target_version'] !== '3.0') {
			$settings->addBody("global \$context, \$txt, \$scripturl" . (empty($skeleton['options']) ? '' : ", \$modSettings") . ";" . PHP_EOL);
			$settings->addBody("loadLanguage(?);" . PHP_EOL, [$classname . (empty($skeleton['use_lang_dir']) ? '' : '/')]);
			$settings->addBody("\$context['page_title'] = \$context['settings_title'] = \$txt['{$snakeName}_title'];");
			$settings->addBody("\$context['post_url'] = \$scripturl . '?action=admin;area=modsettings;save;sa=$snakeName';" . PHP_EOL);
		} else {
			$settings->addBody("Lang::load(?);" . PHP_EOL, [$classname . (empty($skeleton['use_lang_dir']) ? '' : '/')]);
			$settings->addBody("Utils::\$context['page_title'] = Utils::\$context['settings_title'] = Lang::\$txt['{$snakeName}_title'];");
			$settings->addBody("Utils::\$context['post_url'] = Config::\$scripturl . '?action=admin;area=modsettings;save;sa=$snakeName';" . PHP_EOL);
		}

		if (! empty($skeleton['options'])) {
			$this->addDefaultSettings($settings, $skeleton, $snakeName);
		}

		$this->fillConfigVars($settings, $skeleton, $snakeName);

		if (isset($hookKeys[Hook::ADMIN_SEARCH])) {
			$settings->addBody("if (\$return_config)");
			$settings->addBody("\treturn \$config_vars;" . PHP_EOL);
		}

		if ($skeleton['smf_target_version'] !== '3.0') {
			$settings->addBody("\$context[\$context['admin_menu_name']]['tab_data']['description'] = \$txt['{$snakeName}_description'];" . PHP_EOL);
			$settings->addBody("// Saving?");
			$settings->addBody("if (isset(\$_GET['save'])) {");
			$settings->addBody("\tcheckSession();" . PHP_EOL);
			$settings->addBody("\t\$save_vars = \$config_vars;");
			$settings->addBody("\tsaveDBSettings(\$save_vars);" . PHP_EOL);
			$settings->addBody("\tredirectexit('action=admin;area=modsettings;sa=$snakeName');");
			$settings->addBody("}" . PHP_EOL);
			$settings->addBody("prepareDBSettingContext(\$config_vars);");
		} else {
			$settings->addBody("Menu::\$loaded['admin']->tab_data['description'] = Lang::\$txt['{$snakeName}_description'];" . PHP_EOL);
			$settings->addBody("// Saving?");
			$settings->addBody("if (isset(\$_GET['save'])) {");
			$settings->addBody("\tUser::\$me->checkSession();" . PHP_EOL);
			$settings->addBody("\t\$save_vars = \$config_vars;");
			$settings->addBody("\tACP::saveDBSettings(\$save_vars);" . PHP_EOL);
			$settings->addBody("\tUtils::redirectexit('action=admin;area=modsettings;sa=$snakeName');");
			$settings->addBody("}" . PHP_EOL);
			$settings->addBody("ACP::prepareDBSettingContext(\$config_vars);");
		}
	}

	private function generateSettingsArea3(ClassType $class, array &$skeleton, string $classname, string $snakeName): void
	{
		$settings = $class->addMethod('settings');

		if ($skeleton['smf_target_version'] !== '3.0') {
			$settings->addBody("global \$context, \$txt;" . PHP_EOL);
		}

		if ($skeleton['make_template']) {
			if ($skeleton['smf_target_version'] !== '3.0') {
				$settings->addBody("loadTemplate($classname);" . PHP_EOL);
			} else {
				$settings->addBody("Theme::loadTemplate($classname);" . PHP_EOL);
			}
		}

		if ($skeleton['smf_target_version'] !== '3.0') {
			$settings->addBody("require_once dirname(__DIR__) . '/ManageSettings.php';" . PHP_EOL);
			$settings->addBody("\$context['page_title'] = \$txt['{$snakeName}_title'];" . PHP_EOL);
			$settings->addBody("\$subActions = [");
			$settings->addBody("\t'section1'  => [\$this, 'sectionExample1'],");
			$settings->addBody("\t//'section2' => [\$this, 'sectionExample2'],");
			$settings->addBody("];" . PHP_EOL);
			$settings->addBody("\$context[\$context['admin_menu_name']]['tab_data'] = [");
			$settings->addBody("\t'title' => \$txt['{$snakeName}_title'],");
			$settings->addBody("\t'description' => \$txt['{$snakeName}_description'],");
			$settings->addBody("\t'tabs' => [");
			$settings->addBody("\t\t'section1'  => [],");
			$settings->addBody("\t\t//'section2'  => [],");
			$settings->addBody("\t]");
			$settings->addBody("];" . PHP_EOL);
			$settings->addBody("loadGeneralSettingParameters(\$subActions, 'section1');" . PHP_EOL);
			$settings->addBody("call_helper(\$subActions[\$context['sub_action']]);");
		} else {
			$settings->addBody("Utils::\$context['page_title'] = Lang::\$txt['{$snakeName}_title'];" . PHP_EOL);
			$settings->addBody("\$subActions = [");
			$settings->addBody("\t'section1'  => [\$this, 'sectionExample1'],");
			$settings->addBody("\t//'section2' => [\$this, 'sectionExample2'],");
			$settings->addBody("];" . PHP_EOL);
			$settings->addBody("Menu::\$loaded['admin']->tab_data = [");
			$settings->addBody("\t'title' => Lang::\$txt['{$snakeName}_title'],");
			$settings->addBody("\t'description' => Lang::\$txt['{$snakeName}_description'],");
			$settings->addBody("\t'tabs' => [");
			$settings->addBody("\t\t'section1'  => [],");
			$settings->addBody("\t\t//'section2'  => [],");
			$settings->addBody("\t]");
			$settings->addBody("];" . PHP_EOL);
			$settings->addBody("\$subAction = isset(\$_REQUEST['sa']) && isset(\$subActions[\$_REQUEST['sa']]) ? \$_REQUEST['sa'] : 'section1';" . PHP_EOL);
			$settings->addBody("call_user_func(\$subActions[\$subAction]);");
		}

		$this->generateSectionExample($class, $skeleton, $snakeName);
	}

	private function generateSectionExample(ClassType $class, array &$skeleton, string $snakeName): void
	{
		$section = $class->addMethod('sectionExample1');
		$section->addComment('@return array|void');
		$parameter = $section->addParameter('return_config', false);
		$parameter->setType('bool');

		if ($skeleton['smf_target_version'] !== '3.0') {
			$section->addBody("global \$context, \$txt, \$scripturl;" . PHP_EOL);
			$section->addBody("require_once dirname(__DIR__) . '/ManageServer.php';" . PHP_EOL);
			$section->addBody("\$context['page_title'] .= ' - ' . \$txt['{$snakeName}_section1_title'];");
			$section->addBody("\$context['post_url'] = \$scripturl . '?action=admin;area=$snakeName;sa=section1;save';" . PHP_EOL);
		} else {
			$section->addBody("Utils::\$context['page_title'] .= ' - ' . Lang::\$txt['{$snakeName}_section1_title'];");
			$section->addBody("Utils::\$context['post_url'] = Config::\$scripturl . '?action=admin;area=$snakeName;sa=section1;save';" . PHP_EOL);
		}

		$this->fillConfigVars($section, $skeleton, $snakeName);

		$section->addBody("if (\$return_config)");
		$section->addBody("\treturn \$config_vars;" . PHP_EOL);
		$section->addBody("if (isset(\$_GET['save'])) {");

		if ($skeleton['smf_target_version'] !== '3.0') {
			$section->addBody("\tcheckSession();" . PHP_EOL);
			$section->addBody("\tsaveDBSettings(\$config_vars);" . PHP_EOL);
			$section->addBody("\tredirectexit('action=admin;area=$snakeName;sa=section1');");
			$section->addBody("}" . PHP_EOL);
			$section->addBody("prepareDBSettingContext(\$config_vars);");
		} else {
			$section->addBody("\tUser::\$me->checkSession();" . PHP_EOL);
			$section->addBody("\tACP::saveDBSettings(\$config_vars);" . PHP_EOL);
			$section->addBody("\tUtils::redirectexit('action=admin;area=$snakeName;sa=section1');");
			$section->addBody("}" . PHP_EOL);
			$section->addBody("ACP::prepareDBSettingContext(\$config_vars);");
		}
	}

	private function addDefaultSettings(Method $method, array $skeleton, string $snakeName): void
	{
		$method->addBody("// Add default settings");
		$method->addBody("\$addSettings = [];");

		foreach ($skeleton['options'] as $option) {
			if (! empty($option['default'])) {
				if ($skeleton['smf_target_version'] !== '3.0') {
					$method->addBody("if (! isset(\$modSettings['{$snakeName}_{$option['name']}']))");
				} else {
					$method->addBody("if (! isset(Config::\$modSettings['{$snakeName}_{$option['name']}']))");
				}

				$method->addBody("\t\$addSettings['{$snakeName}_{$option['name']}'] = {$this->getDefaultValue($option)};");
			}
		}

		if ($skeleton['smf_target_version'] !== '3.0') {
			$method->addBody("updateSettings(\$addSettings);" . PHP_EOL);
		} else {
			$method->addBody("Config::updateModSettings(\$addSettings);" . PHP_EOL);
		}
	}

	private function fillConfigVars(Method $method, array &$skeleton, string $snakeName): void
	{
		$method->addBody("\$config_vars = [");

		if (! empty($skeleton['options'])) {
			foreach ($skeleton['options'] as $option) {
				if (in_array($option['type'], ['select-multiple', 'select'])) {
					$isMultiple = var_export($option['type'] === 'select-multiple', true);
					$option['type'] = 'select';

					$method->addBody(
						"\t['{$option['type']}', '{$snakeName}_{$option['name']}', \$txt['$snakeName']['{$option['name']}_set'], 'multiple' => $isMultiple],"
					);
				} else {
					$method->addBody("\t['{$option['type']}', '{$snakeName}_{$option['name']}'],");
				}

				if ($option['type'] === 'callback') {
					$skeleton['callbacks'][] = $option['name'];
				}
			}
		} else {
			$method->addBody("\t// ['check', '{$snakeName}_enable'],");
		}

		$method->addBody("];" . PHP_EOL);
	}

	private function generateScheduledTasks(array &$tasks, array $skeleton, string $baseClassname): void
	{
		foreach ($skeleton['scheduled_tasks'] as $id => $task) {
			$classname = $this->toCamelCase($task['slug']);
			$filename = $classname . '.php';

			$targetTaskClass = $skeleton['smf_target_version'] === '3.0'
				? 'SMF\Tasks\ScheduledTask'
				: 'SMF_BackgroundTask';
			$namespace = new PhpNamespace($skeleton['author'] . '\\' . $baseClassname . '\\Tasks');
			$namespace->addUse($targetTaskClass);

			$class = $namespace->addClass($classname);
			$class->setExtends($targetTaskClass);
			$class->addComment('Generated by ' . SMM_NAME);

			$skeleton['scheduled_tasks'][$id]['callable'] =
				"\\\\{$skeleton['author']}\\\\$baseClassname\\\\Tasks\\\\$classname::execute";

			$method = $class->addMethod('execute');
			$method->setReturnType('bool');

			if ($skeleton['smf_target_version'] !== '3.0') {
				$method->addBody("global \$smcFunc;" . PHP_EOL);
			}

			$method->addBody("// Add your code here" . PHP_EOL);
			$method->addBody("// Return true if everything is OK");
			$method->addBody("return true;");

			$tasks[$task['slug']]['content'] = $this->getGeneratedContent($namespace, $filename, $skeleton);
			$tasks[$task['slug']]['filename'] = $filename;
		}
	}

	private function generateBackgroundTasks(array &$tasks, array $skeleton, string $baseClassname): void
	{
		foreach ($skeleton['background_tasks'] as $id => $task) {
			$classname = $task['classname'];
			$filename = $classname . '.php';

			$targetTaskClass = $skeleton['smf_target_version'] === '3.0'
				? 'SMF\Tasks\BackgroundTask'
				: 'SMF_BackgroundTask';
			$namespace = new PhpNamespace($skeleton['author'] . '\\' . $baseClassname . '\\Tasks');
			$namespace->addUse($targetTaskClass);
			$namespace->addUse('SMF\Db\DatabaseApi', 'Db');

			$class = $namespace->addClass($classname);
			$class->setExtends($targetTaskClass);
			$class->addComment('Generated by ' . SMM_NAME);

			$skeleton['background_tasks'][$id]['callable'] =
				"\\\\{$skeleton['author']}\\\\$baseClassname\\\\Tasks\\\\$classname";

			$method = $class->addMethod('execute');
			$method->setReturnType('bool');

			if ($skeleton['smf_target_version'] !== '3.0') {
				$method->addBody("global \$smcFunc;" . PHP_EOL);
			}

			$method->addBody("// Add your code here" . PHP_EOL);

			if (empty($task['regularity'])) {
				$method->addBody("// Return true if everything is OK");
				$method->addBody("return true;");
			} else {
				$regularity = $task['regularity'] == 1 ? 1 : 7;
				$method->addBody("// Run task again if you need");
				$method->addBody("\$regularity = $regularity * 24 * 60 * 60;" . PHP_EOL);

				if ($skeleton['smf_target_version'] !== '3.0') {
					$method->addBody("return (bool) \$smcFunc['db_insert']('insert',");
				} else {
					$method->addBody("return (bool) Db::\$db->insert('insert',");
				}

				$method->addBody("\t'{db_prefix}background_tasks',");
				$method->addBody("\t[");
				$method->addBody("\t\t'task_file'    => 'string',");
				$method->addBody("\t\t'task_class'   => 'string',");
				$method->addBody("\t\t'task_data'    => 'string',");
				$method->addBody("\t\t'claimed_time' => 'int'");
				$method->addBody("\t],");
				$method->addBody("\t[");
				$method->addBody("\t\t'\$sourcedir/$baseClassname/Tasks/$filename',");
				$method->addBody("\t\t'\\\\' . self::class,");
				$method->addBody("\t\t'',");
				$method->addBody("\t\ttime() + \$regularity");
				$method->addBody("\t],");
				$method->addBody("\t['id_task'],");
				$method->addBody("\t1");
				$method->addBody(");" . PHP_EOL);
			}

			$tasks[$classname]['content'] = $this->getGeneratedContent($namespace, $filename, $skeleton);
			$tasks[$classname]['filename'] = $filename;
		}
	}

	private function generateTaskExamples(ClassType $class, array $skeleton, string $baseClassname, array $tasks): void
	{
		if (empty($tasks)) {
			return;
		}

		foreach ($skeleton['background_tasks'] as $task) {
			if (! array_key_exists($task['classname'], $tasks)) {
				continue;
			}

			$classname = $task['classname'];
			$filename  = $tasks[$classname]['filename'];

			$method = $class->addMethod('run' . $task['classname']);
			$method->setReturnType('void');

			$method->addComment('Call this method to run a background task');

			if ($skeleton['smf_target_version'] !== '3.0') {
				$method->addBody("global \$smcFunc;" . PHP_EOL);
				$method->addBody("\$smcFunc['db_insert']('insert',");
			} else {
				$method->addBody("Db::\$db->insert('insert',");
			}

			$method->addBody("\t'{db_prefix}background_tasks',");
			$method->addBody("\t[");
			$method->addBody("\t\t'task_file'  => 'string',");
			$method->addBody("\t\t'task_class' => 'string',");
			$method->addBody("\t\t'task_data'  => 'string'");
			$method->addBody("\t],");
			$method->addBody("\t[");
			$method->addBody("\t\t'\$sourcedir/$baseClassname/Tasks/$filename',");
			$method->addBody("\t\t'{$task['callable']}',");
			$method->addBody("\t\t''");
			$method->addBody("\t],");
			$method->addBody("\t['id_task']");
			$method->addBody(");" . PHP_EOL);
		}
	}

	private function getGeneratedContent(PhpNamespace $namespace, string $filename, array $skeleton): string
	{
		$file = new PhpFile();
		$file->addNamespace($namespace);
		$file->addComment($filename);

		return (new Printer())->printFile($this->addLicenseBlock($file, $skeleton));
	}

	private function addLicenseBlock(PhpFile $file, array $skeleton): PhpFile
	{
		$license = $skeleton['license_data'];

		$file->addComment('');
		$file->addComment("@package {$skeleton['name']}");
		$file->addComment("@link {$skeleton['site']}");
		$file->addComment("@author {$skeleton['author']} <{$skeleton['email']}>");
		$file->addComment("@copyright " . date('Y') . " {$skeleton['author']}");
		$file->addComment("@license {$license['link']} {$license['full_name']}");
		$file->addComment('');
		$file->addComment("@version " . $skeleton['version']);

		return $file;
	}

	private function getDefaultValue(array $option): string
	{
		$default = match ($option['type']) {
			'int'   => (int) $option['default'],
			'float' => (float) $option['default'],
			default => $option['default'],
		};

		return var_export($default, true);
	}

	private function getMethodName(string $hook): string
	{
		return lcfirst(str_replace(' ', '', ucwords(strtr($hook, ['integrate' => '', '_' => ' ']))));
	}

	private function toCamelCase(string $value): string
	{
		return str_replace(' ', '', ucwords(str_replace('_', ' ', $value)));
	}
}
